"""add description and budget to project

Revision ID: 0f80c22f9eba
Revises: d1e81671c21d
Create Date: 2025-05-11 23:26:23.985439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f80c22f9eba'
down_revision: Union[str, None] = 'd1e81671c21d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('description', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('budget', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'budget')
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###
